# -*- coding: utf-8 -*-
"""DiscountVsTotalSales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ygQMISIUwM9B9DV7h5mmGjQxmLYahYv5
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/VarunPalrecha/DataSets/main/output1.csv')
df

X = df[['discount']]
X

df['sales'] = df[['sales_month1', 'sales_month2', 'sales_month3']].sum(axis=1)
y = df['sales'].values
y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=52)

model = RandomForestRegressor(n_estimators=100, random_state=52)
model.fit(X_train, y_train)

predicted_sales = model.predict(X_test)
predicted_sales

plt.figure(figsize=(10, 6))

plt.scatter(X_test, y_test, color='blue', label='Actual Data')

sorted_indices = np.argsort(X_test.values.ravel())
plt.plot(X_test.values[sorted_indices], predicted_sales[sorted_indices], color='red', linewidth=2, label='Predicted Values')
plt.xlabel('Discount')
plt.ylabel('Total Sales')
plt.title('Discount vs. Total Sales (Random Forest)')
plt.legend()
plt.grid(True)
plt.show()