# -*- coding: utf-8 -*-
"""SalesVsNegative.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gVxy8ILCCapUe1HviztBC2r8gGFV4VXr
"""

import pandas as pd
import ast
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

data = pd.read_csv('https://raw.githubusercontent.com/VarunPalrecha/DataSets/main/output1.csv')
data

X = data[['negativeReviews']].values
X

data['sales'] = data[['sales_month1', 'sales_month2', 'sales_month3']].sum(axis=1)
y = data['sales'].values
y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred

rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f'Root Mean Squared Error: {rmse}')

new_negative_reviews = [[12]]  # Example new positiveReviews value
predicted_sales = model.predict(new_negative_reviews)
print(f'Predicted Sales for New Negative Reviews: {predicted_sales[0]}')