# -*- coding: utf-8 -*-
"""SalesVsSeller.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/161awvCl18B_06Et-qJjnMpJCrvFs7gTH
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error

data = pd.read_csv('https://raw.githubusercontent.com/VarunPalrecha/DataSets/main/output1.csv')
data

X = data[['seller']]
X

data['sales'] = data[['sales_month1', 'sales_month2', 'sales_month3']].sum(axis=1)
y = data['sales'].values
y

column_transformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_encoded = column_transformer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred

rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f'Root Mean Squared Error: {rmse}')

new_seller = [['eBay']]  # Example new seller value
new_seller_encoded = column_transformer.transform(new_seller)
predicted_sales = model.predict(new_seller_encoded)
print(f'Predicted Sales for New Seller: {predicted_sales[0]}')